import time
x = 1
while x == 1:
    print("######&#####")
    time.sleep(0.1)
    print("######&#####")
    time.sleep(0.1)
    print("######&#####")
    time.sleep(0.1)
    print("#####&######")
    time.sleep(0.1)
    print("####&#######")
    time.sleep(0.1)
    print("###&########")
    time.sleep(0.1)
    print("##&#########")
    time.sleep(0.1)
    print("#&##########")
    time.sleep(0.1)
    print("&###########")
    time.sleep(0.1)
    print("#&##########")
    time.sleep(0.1)
    print("##&#########")
    time.sleep(0.1)
    print("###&########")
    time.sleep(0.1)
    print("####&#######")
    time.sleep(0.1)
    print("#####&######")
    time.sleep(0.1)

